spring.application.name=faultlens

spring.datasource.url=jdbc:postgresql://localhost:5432/faultlens_db
spring.datasource.username=postgres
<<<<<<< HEAD
spring.datasource.password={db_password}
=======
spring.datasource.password=${DB_PASSWORD}
>>>>>>> 242d5f8 (feat: add monitored service management API)

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080


